apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: search-replicaset
  namespace: p-spring-search
  labels:
    app: search-product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-product
  template:
    metadata:
      labels:
        app: search-product
    spec:
      nodeSelector:
        workload: search
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: search
          image: danysoftdev/p-spring-search:latest
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: maria-search-secret
